// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5kDOwH7-VsGsSt4ZqZS1YRUqOff4veT0',
    appId: '1:235008057315:web:200f38a5fd4e8e84b48ad6',
    messagingSenderId: '235008057315',
    projectId: 'swiftcart-main',
    authDomain: 'swiftcart-main.firebaseapp.com',
    storageBucket: 'swiftcart-main.firebasestorage.app',
    measurementId: 'G-PDV0ES4CJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFDkwHXvW4W-cotbyf_N-KHwSh3J-T4Ks',
    appId: '1:235008057315:android:3308103dac996edfb48ad6',
    messagingSenderId: '235008057315',
    projectId: 'swiftcart-main',
    storageBucket: 'swiftcart-main.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4M6Eic664wSBVEXcFf445aZpF1E1PJuk',
    appId: '1:235008057315:ios:4f8180ca6b285878b48ad6',
    messagingSenderId: '235008057315',
    projectId: 'swiftcart-main',
    storageBucket: 'swiftcart-main.firebasestorage.app',
    iosClientId: '235008057315-eke3a819lcvskv68jv3o63mhsn2vshl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftcartAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4M6Eic664wSBVEXcFf445aZpF1E1PJuk',
    appId: '1:235008057315:ios:4f8180ca6b285878b48ad6',
    messagingSenderId: '235008057315',
    projectId: 'swiftcart-main',
    storageBucket: 'swiftcart-main.firebasestorage.app',
    iosClientId: '235008057315-eke3a819lcvskv68jv3o63mhsn2vshl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftcartAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5kDOwH7-VsGsSt4ZqZS1YRUqOff4veT0',
    appId: '1:235008057315:web:a7a6f736518834b9b48ad6',
    messagingSenderId: '235008057315',
    projectId: 'swiftcart-main',
    authDomain: 'swiftcart-main.firebaseapp.com',
    storageBucket: 'swiftcart-main.firebasestorage.app',
    measurementId: 'G-PGHP8KSMN8',
  );
}
